[package]
name = "crabxl-python"
version = "0.1.0-alpha.10"
edition = "2024"
rust-version = "1.99"
license = "MIT"
repository = "https://github.com/crabxl/crabxl-python"
description = "Optional Python compatibility adapter for crabxl"

[lib]
name = "_native"
crate-type = ["cdylib"]

[features]
default = ["deflate-zlib-rs"]
deflate-zlib-rs = ["crabxl/deflate-zlib-rs"]
deflate-zlib = ["crabxl/deflate-zlib"]

[dependencies]
crabxl = { version = "=0.1.0-alpha.10", git = "https://github.com/crabxl/crabxl.git", rev = "497417f6d5fa776a86641b98714567956b04433f", default-features = false }
pyo3 = { version = "0.29.3", features = ["extension-module"] }
tempfile = "3.27"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"

[profile.release]
lto = "thin"
